### ISSUE TITLE
Unable to val

### ISSUE THREAD

**Issue by Him-wen** [cv516Buaa/tph-yolov5#2]
Hello author, the following error occurred in the reasoning process, please advise, thank you。
AttributeError: Can't get attribute 'NonDynamicallyQuantizableLinear' on <module 'torch.nn.modules.linear' from '/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/linear.py'>

**Comment by cv516Buaa** [comment]
This problem may be caused by the version of torch.
The "yolov5l-xs-1.pt" and "yolov5l-xs-2.pt" is trained with PyTorch v1.10.
You can update torch to v1.10 or train your own weight use train.py.

**Comment by Him-wen** [comment]
Ok, thanks author
