### ISSUE TITLE
 ret = input.softmax(dim) RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by RoyCopterPix** [cv516Buaa/tph-yolov5#23]
Hey,

When I am trying to run the inference command I am getting the next error:
ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 962.00 MiB (GPU 0; 3.81 GiB total capacity; 1.79 GiB already allocated; 725.00 MiB free; 1.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I tried to change the batch to 4 and even to 2 but it doesn't solve the problem.

What can I do to solve this?

**Comment by maarten0912** [comment]
Have you tried a batch size of 1?

**Comment by RoyCopterPix** [comment]
> 

yeah I tried it too.

I have GTX 1650, it is werid. I even tried on a different computer just to be sure I am doing everything right with Quadro M1000M and I get the same error. 

what do I have to change in the code to fix that issue?

**Comment by RoyCopterPix** [comment]
> Have you tried a batch size of 1?

yeah I tried it too.

I have GTX 1650, it is werid. I even tried on a different computer just to be sure I am doing everything right with Quadro M1000M and I get the same error.

what do I have to change in the code to fix that issue?

**Comment by RoyCopterPix** [comment]
Note: I am getting this warning too when running the inference.
WARNING: --img-size 1996 must be multiple of max stride 32, updating to 2016

maybe that's the reason for the error?

**Comment by maarten0912** [comment]
> Note: I am getting this warning too when running the inference. WARNING: --img-size 1996 must be multiple of max stride 32, updating to 2016
> 
> maybe that's the reason for the error?

No, this should not be an issue.

Your graphics card probably just has too little memory to perform these large inferences. On my NVIDIA GeForce RTX 3060 Ti (8 GB of VRAM), I can also barely run batch size of 3. For me batch size 1 requires 5GiB of VRAM, and every batch size increase requires  1GiB more (and that is all on top of basic system usage).

If it even doesn't work for you with batch size of 1, you should probably lower the image size, which would significantly lower the memory needs.

If you really need 1996 pixel inference, you can consider using another GPU or cloud computing for it.

**Comment by RoyCopterPix** [comment]
> > Note: I am getting this warning too when running the inference. WARNING: --img-size 1996 must be multiple of max stride 32, updating to 2016
> > maybe that's the reason for the error?
> 
> No, this should not be an issue.
> 
> Your graphics card probably just has too little memory to perform these large inferences. On my NVIDIA GeForce RTX 3060 Ti (8 GB of VRAM), I can also barely run batch size of 3. For me batch size 1 requires 5GiB of VRAM, and every batch size increase requires 1GiB more (and that is all on top of basic system usage).
> 
> If it even doesn't work for you with batch size of 1, you should probably lower the image size, which would significantly lower the memory needs.
> 
> If you really need 1996 pixel inference, you can consider using another GPU or cloud computing for it.

Thanks for the help, reducing the image size did the job.
