### ISSUE TITLE
WBF

### ISSUE THREAD

**Issue by xiaoyi-creator** [cv516Buaa/tph-yolov5#3]
I want to ask where WBF is defined and called

**Comment by cv516Buaa** [comment]
The input of wbf.py is the result of val.py.
For example, after you use val.py with two different weights, you will get two results in the folder yolov5/runs/val.
wbf.py will merge these results and ouput a better ensemble result.

**Comment by wonkicho** [comment]
Hello, I have a question about above things.
if i use below infer command
"python val.py --weights ./weights/yolov5l-xs-1.pt ./weights/yolov5l-xs-2.pt --img 1996 --data ./data/VisDrone.yaml
                                    --augment --save-txt  --save-conf --task val --batch-size 8 --verbose --name v5l-xs"
can i see two results in "yolov5/runs/val"?
there is only one folders.

**Comment by cv516Buaa** [comment]
if you use
```
python val.py --weights ./weights/yolov5l-xs-1.pt ./weights/yolov5l-xs-2.pt --img 1996 --data ./data/VisDrone.yaml
--augment --save-txt --save-conf --task val --batch-size 8 --verbose --name v5l-xs
```
you will only get 1 folder, because yolov5 will use nms to merge two model.
to use wbf, you should val the model seperatly：
```
python val.py --weights ./weights/yolov5l-xs-1.pt --img 1996 --data ./data/VisDrone.yaml --augment --save-txt --save-conf --task val --batch-size 8 --verbose --name v5l-xs1
python val.py --weights ./weights/yolov5l-xs-2.pt --img 1996 --data ./data/VisDrone.yaml --augment --save-txt --save-conf --task val --batch-size 8 --verbose --name v5l-xs2
```
Then you will get two folder.
After that you can use wbf to merge these two result.

**Comment by VicxCreine** [comment]
> 
Hello, is there a way to test the mAP of the ensemble result?
