### ISSUE TITLE
TPH

### ISSUE THREAD

**Issue by sandy-0326** [cv516Buaa/tph-yolov5#4]
I want to know where the TPH module is？
And  I want to know whether the network structure described in the file "yolov5l-xs-tr-cbam-spp-bifpn.yaml" is consistent with the network structure described in the paper.

**Comment by cv516Buaa** [comment]
Transformer prediction head is the combination of transformer block with yolo pretiction head,
![image](https://user-images.githubusercontent.com/94512783/143565108-5206e12e-a1b7-4c1e-a21c-347d58757671.png)
 C3TR block with the prediction head together form TPH.
"yolov5l-xs-tr-cbam-spp-bifpn.yaml" is not consistent with network structure described in the paper, it only use one tph module with some extra layer for the balance of speed and precision，but the structure in paper use 4 tph module.

**Comment by sandy-0326** [comment]
> Transformer prediction head is the combination of transformer block with yolo pretiction head, ![image](https://user-images.githubusercontent.com/94512783/143565108-5206e12e-a1b7-4c1e-a21c-347d58757671.png) C3TR block with the prediction head together form TPH. "yolov5l-xs-tr-cbam-spp-bifpn.yaml" is not consistent with network structure described in the paper, it only use one tph module with some extra layer for the balance of speed and precision，but the structure in paper use 4 tph module.
Thank you! I get it.
