### ISSUE TITLE
About SwinTransformer

### ISSUE THREAD

**Issue by SehunKing** [cv516Buaa/tph-yolov5#7]
yolov5l-xs-tph.yaml中定义的模型似乎将Transformer替换为了SwinTransformer，且去掉了CBAM模块，请问这样做带来的精度和速度有何变化吗？

**Comment by cv516Buaa** [comment]
您好，这样做会在占用显存和模型训练速度上带来提升，这样就可以使用更大的输入图像和批次大小进行训练，精度其实没什么变化。

**Comment by SehunKing** [comment]
感谢您的解答！
