### ISSUE TITLE
Converted model gives error on TensorRT

### ISSUE THREAD

**Issue by maarten0912** [cv516Buaa/tph-yolov5#8]
I want to use the yolov5l-xs-1.pt model to perform inference and optimize it using TensorRT. I understand you are not using TensorRT, but I thought you might understand the issue

 I have exported the .pt file to an onnx file using the `export.py` program (without `--dynamic` flag). It gave this warning, but I don't understand what it means:
```
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```
Later, when loading the ONNX file with TensorRT, I get this error:
```
[TensorRT] ERROR: [graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 9: Internal Error (Reshape_218: reshape changes volume)
```

Apparently there is a node which reshapes to a different volume, which is not allowed according to TensorRT. Do you know what I can do about this issue? Please let me know if you could use more information!

EDIT:
I have also tried it with the `--dynamic` flag. It looks like it is going through more of the ONNX model when loading, but eventually it gives this error:
```
[TRT]    4: [network.cpp::validate::2713] Error Code 4: Internal Error (images: dynamic input is missing dimensions in profile 0.)
```

EDIT:
This is what the node (from the non-dynamic model) looks like:
![image](https://user-images.githubusercontent.com/57093022/145824737-8aad1c5d-cfc9-40c3-bdde-0df993e25a6b.png)

**Comment by maarten0912** [comment]
I got it working by just using a whole other repository to optimize the ONNX with TRT. I now am using https://github.com/BlueMirrors/Yolov5-TensorRT. For this one I am using the `--dynamic` option, and later I optimize it with the image size that I like.

**Comment by RoyCopter** [comment]
@maarten0912 Hey Maarten how did you convert the pt to onnx? 
and just to be sure, after you convert it to TensorRT, how do you run your new weights with the TPH-Yolov5 repository? 
thanks!

**Comment by maarten0912** [comment]
I don't use Yolov5-TensorRT anymore, right now I am using [TensorRTx](https://github.com/wang-xinyu/tensorrtx) and the yolov5 folder in it. You should convert your .pt model to a .wts file (explained in the yolov5 directory) and then you can use TensorRTx to generate a .engine file. I'm not using ONNX anymore.

**Comment by RoyCopter** [comment]
> I don't use Yolov5-TensorRT anymore, right now I am using [TensorRTx](https://github.com/wang-xinyu/tensorrtx) and the yolov5 folder in it. You should convert your .pt model to a .wts file (explained in the yolov5 directory) and then you can use TensorRTx to generate a .engine file. I'm not using ONNX anymore.

thanks!

I already used the TensorRTx so it's great.

I do manage to generate the  yolov5-xs-1.wts file from the yolov5l-xs-1.pt using the export.py in the tph-yolov5 folder.  

But I can't manage to generate the engine file..  
when I try to generate it with :
sudo ./yolov5 -s yolov5l-xs-1.wts yolov5-xs-1.engine l

I get the next error:
(unnamed Layer* 225) [Convolution]:kernel weights has count 2097152 but 524288 was expected with additional errors with the 225 layer.. 

How do you manage to generate the engine file and how you run the model with the engine weights?

**Comment by RoyCopter** [comment]
> I don't use Yolov5-TensorRT anymore, right now I am using [TensorRTx](https://github.com/wang-xinyu/tensorrtx) and the yolov5 folder in it. You should convert your .pt model to a .wts file (explained in the yolov5 directory) and then you can use TensorRTx to generate a .engine file. I'm not using ONNX anymore.

@maarten0912 
any idea man?

**Comment by maarten0912** [comment]
You should modify the TensorRTx to work with the components of TPH-YOLOv5. Now it only works with standard YOLOv5
